In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
dataset=pd.read_csv("Copy of PhD_Dataset_Incidence.csv")
dataset

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
0,1.0,1,3.0,1,6,1,4,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,2.0,3.0,1.0
1,2.0,1,3.0,1,7,1,7,7,6,1,...,1.0,0.5,5.0,2,0.0,0,0,2.0,3.0,1.0
2,3.0,1,3.0,1,6,1,5,5,6,1,...,1.0,0.5,2.0,0,0.0,0,0,2.0,3.0,1.0
3,4.0,1,3.0,1,6,1,6,3,6,1,...,1.0,0.5,4.0,0,0.0,0,2,2.0,2.0,1.0
4,5.0,1,4.0,1,5,1,10,7,6,1,...,1.0,3.0,10.0,2,0.0,0,0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,2,2.0,5,2,2,5,1,4,1,...,1.0,10.0,2.0,1,0.0,0,0,NaN,2.0,2.0
495,NaN,1,2.0,5,6,4,5,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,NaN,3.0,2.0
496,NaN,1,3.0,5,5,4,4,3,7,1,...,1.0,4.0,0.0,0,0.0,0,0,2.0,3.0,1.0
497,NaN,1,3.0,5,3,1,4,2,4,2,...,1.0,1.0,4.0,2,0.0,2,0,1.0,NaN,2.0
498,NaN,1,3.0,5,4,1,5,2,3,2,...,1.0,1.0,4.0,4,0.0,0,1,1.0,3.0,1.0

In [11]:

dataset.columns=dataset.columns.str.lower()
dataset

,hh,sex,age,lga,edu,mrt_status,fmly_size,m_income,cfuel,ipollut,...,h_facility,dist_hfacility,illiness,waterborne,resp_disease,eye_disease,child_death,maternalcare,square_meal,health_ins
0,1.0,1,3.0,1,6,1,4,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,2.0,3.0,1.0
1,2.0,1,3.0,1,7,1,7,7,6,1,...,1.0,0.5,5.0,2,0.0,0,0,2.0,3.0,1.0
2,3.0,1,3.0,1,6,1,5,5,6,1,...,1.0,0.5,2.0,0,0.0,0,0,2.0,3.0,1.0
3,4.0,1,3.0,1,6,1,6,3,6,1,...,1.0,0.5,4.0,0,0.0,0,2,2.0,2.0,1.0
4,5.0,1,4.0,1,5,1,10,7,6,1,...,1.0,3.0,10.0,2,0.0,0,0,1.0,3.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,NaN,2,2.0,5,2,2,5,1,4,1,...,1.0,10.0,2.0,1,0.0,0,0,NaN,2.0,2.0
495,NaN,1,2.0,5,6,4,5,4,6,1,...,1.0,1.0,2.0,0,0.0,0,0,NaN,3.0,2.0
496,NaN,1,3.0,5,5,4,4,3,7,1,...,1.0,4.0,0.0,0,0.0,0,0,2.0,3.0,1.0
497,NaN,1,3.0,5,3,1,4,2,4,2,...,1.0,1.0,4.0,2,0.0,2,0,1.0,NaN,2.0
498,NaN,1,3.0,5,4,1,5,2,3,2,...,1.0,1.0,4.0,4,0.0,0,1,1.0,3.0,1.0

In [12]:
dataset.dtypes

hh                float64
sex                 int64
age               float64
lga                 int64
edu                 int64
mrt_status          int64
fmly_size           int64
m_income            int64
cfuel               int64
ipollut             int64
rbiomass          float64
dailycook         float64
avl_lpg             int64
aff_lpg             int64
electricity       float64
hrs_elect         float64
aff_elct          float64
exp_elct           object
source_light      float64
exp_lpg            object
exp_nonlpg         object
aff_solide          int64
hh_appl             int64
edu_appl            int64
c_appl              int64
occupation          int64
hh_exp             object
housing           float64
wall              float64
floor             float64
rooms             float64
bank              float64
bank_acct         float64
b_facility        float64
road              float64
raod_dist           int64
schl                int64
type_sch          float64
dst_sch           float64
sch_days            int64
sch_drpout          int64
chld_labor        float64
h_facility        float64
dist_hfacility    float64
illiness          float64
waterborne          int64
resp_disease      float64
eye_disease         int64
child_death         int64
maternalcare      float64
square_meal       float64
health_ins        float64
dtype: object

In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 52 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hh              167 non-null    float64
 1   sex             499 non-null    int64
 2   age             497 non-null    float64
 3   lga             499 non-null    int64
 4   edu             499 non-null    int64
 5   mrt_status      499 non-null    int64
 6   fmly_size       499 non-null    int64
 7   m_income        499 non-null    int64
 8   cfuel           499 non-null    int64
 9   ipollut         499 non-null    int64
 10  rbiomass        374 non-null    float64
 11  dailycook       497 non-null    float64
 12  avl_lpg         499 non-null    int64
 13  aff_lpg         499 non-null    int64
 14  electricity     497 non-null    float64
 15  hrs_elect       499 non-null    float64
 16  aff_elct        485 non-null    float64
 17  exp_elct        499 non-null    object
 18  source_light    441 non-null    float64
 19  exp_lpg         499 non-null    object
 20  exp_nonlpg      499 non-null    object
 21  aff_solide      499 non-null    int64
 22  hh_appl         499 non-null    int64
 23  edu_appl        499 non-null    int64
 24  c_appl          499 non-null    int64
 25  occupation      499 non-null    int64
 26  hh_exp          466 non-null    object
 27  housing         491 non-null    float64
 28  wall            475 non-null    float64
 29  floor           484 non-null    float64
 30  rooms           484 non-null    float64
 31  bank            495 non-null    float64
 32  bank_acct       498 non-null    float64
 33  b_facility      494 non-null    float64
 34  road            486 non-null    float64
 35  raod_dist       499 non-null    int64
 36  schl            499 non-null    int64
 37  type_sch        488 non-null    float64
 38  dst_sch         456 non-null    float64
 39  sch_days        499 non-null    int64
 40  sch_drpout      499 non-null    int64
 41  chld_labor      498 non-null    float64
 42  h_facility      493 non-null    float64
 43  dist_hfacility  464 non-null    float64
 44  illiness        494 non-null    float64
 45  waterborne      499 non-null    int64
 46  resp_disease    498 non-null    float64
 47  eye_disease     499 non-null    int64
 48  child_death     499 non-null    int64
 49  maternalcare    486 non-null    float64
 50  square_meal     471 non-null    float64
 51  health_ins      498 non-null    float64
dtypes: float64(26), int64(22), object(4)
memory usage: 202.8+ KB

In [19]:
dataset['hh']=dataset['hh'].fillna(0).astype(int)
dataset['m_income']=dataset['m_income'].astype(float)
dataset['cfuel']=dataset['cfuel'].astype('category')
dataset['electricity']=dataset['electricity'].astype('category')

In [21]:
dataset['m_income']=pd.to_numeric(dataset['m_income'],errors='coerce')

In [22]:
print(dataset.dtypes)

hh                   int64
sex                  int64
age                float64
lga                  int64
edu                  int64
mrt_status           int64
fmly_size            int64
m_income           float64
cfuel             category
ipollut              int64
rbiomass           float64
dailycook          float64
avl_lpg              int64
aff_lpg              int64
electricity       category
hrs_elect          float64
aff_elct           float64
exp_elct            object
source_light       float64
exp_lpg             object
exp_nonlpg          object
aff_solide           int64
hh_appl              int64
edu_appl             int64
c_appl               int64
occupation           int64
hh_exp              object
housing            float64
wall               float64
floor              float64
rooms              float64
bank               float64
bank_acct          float64
b_facility         float64
road               float64
raod_dist            int64
schl                 int64
type_sch           float64
dst_sch            float64
sch_days             int64
sch_drpout           int64
chld_labor         float64
h_facility         float64
dist_hfacility     float64
illiness           float64
waterborne           int64
resp_disease       float64
eye_disease          int64
child_death          int64
maternalcare       float64
square_meal        float64
health_ins         float64
dtype: object

In [23]:
dataset.to_csv("cleaned_dataset.csv",index=False)